<?php $helper = $this->helper('Lailson\Biz\Helper\Data');?>

<?php if($helper->getIsModuleEnable()):?>

<div id="modal-overlay" style="display:none;">
    <div class="overlay-content">
        <div class="title">
            <h2><?= $helper->getModalTitle()?></h2>
        </div>
        <p><?= $helper->getModalDescription()?></p>
        <form method="post" action="#" id="modal-overlay-form-validate" autocomplete="off" data-mage-init='{"validation":{}}'
              data-hasrequired="<?= /* @escapeNotVerified */
              __('* Required Fields') ?>">
            <div class="modal-overlay-form">
                <fieldset class="fieldset">
                    <div class="field required">
                        <label for="email_address" class="label"><span><?= __('Email') ?></span></label>
                        <div class="control">
                            <input type="email" name="email" id="email_address" value="" title="<?= __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                </fieldset>
                <fieldset class="fieldset div-button">
                    <div class="primary">
                        <button class="action primary btn-place-order custom-final-checkout-btn" id="submit-button-modal-overlay">
                            <span><?= __('Save') ?></span>
                        </button>
                    </div>
                </fieldset>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "modal_overlay": {
                        "component": "Lailson_Biz/js/modal"
                    }
                 }
            }
        }
    }
</script>
<script type="text/javascript">
    require(
        [
            'jquery',
            'mage/validation'
        ], function(jQuery){
            jQuery(document).ready(function () {
                jQuery("#modal-overlay-form-validate").on('submit',function (e) {
                    e.preventDefault();
                    var dataForm = jQuery('#modal-overlay-form-validate');
                    dataForm.mage('validation', {});
                    var status = dataForm.validation('isValid');
                    var data = jQuery(this).serialize();
                    if(status){
                        jQuery.ajax({
                            url:  'http://projetos.bleez/newsletter/modal/index',
                            type: 'POST',
                            data: data,
                            success: function(response){
                                var modal_overlay_element = jQuery('#modal-overlay');
                                modal_overlay_element.modal('closeModal');
                            },
                            error: function(){
                            }
                        });
                    }
                });
            });
        }
    );
</script>

<?php endif;?>
